nelmio_security:
    csp:
        enabled: true
        report_logger_service: logger
        enforce:
            level1_fallback: false
            browser_adaptive:
                enabled: false
            report-uri: '%router.request_context.base_url%/nelmio/csp/report'
            default-src: ['self', '%env(string:default::ADDITIONAL_CSP_ORIGIN)%']
            style-src: ['self', 'unsafe-inline']
            frame-ancestors: ['none']
            block-all-mixed-content: true
