nelmio_security:
    csp:
        enabled: true
        report_logger_service: logger
        enforce:
            level1_fallback: false
            browser_adaptive:
                enabled: false
            report-uri: '%router.request_context.base_url%/nelmio/csp/report'
            default-src: ['self']
            script-src: ['%env(ASSETS_ORIGIN)%']
            style-src: ['%env(ASSETS_ORIGIN)%', 'unsafe-inline']
            font-src: ['%env(ASSETS_ORIGIN)%']
            img-src: ['self', '%env(ASSETS_ORIGIN)%']
            frame-ancestors: ['none']
            block-all-mixed-content: true

    # prevents framing of the entire site
    clickjacking:
        paths:
            '^/.*': DENY

    # disables content type sniffing for script resources
    content_type:
        nosniff: true

    # forces Microsoft's XSS-Protection with
    # its block mode
    xss_protection:
        enabled: true
        mode_block: true
        report_uri: '%router.request_context.base_url%/nelmio/xss/report'

    # Send a full URL in the `Referer` header when performing a same-origin request,
    # only send the origin of the document to secure destination (HTTPS->HTTPS),
    # and send no header to a less secure destination (HTTPS->HTTP).
    # If `strict-origin-when-cross-origin` is not supported, use `no-referrer` policy,
    # no referrer information is sent along with requests.
    referrer_policy:
        enabled: true
        policies:
            - 'no-referrer'
            - 'strict-origin-when-cross-origin'
