twig:
    file_name_pattern: '*.twig'
    globals:
        locales: '%app.locales%'
        analytics_tag: '%env(ANALYTICS_TAG)%'
    form_themes: ['fragments/form-layout.html.twig']

when@test:
    twig:
        strict_variables: true
