
USE athorrent;

RENAME TABLE user_role TO user_has_role;

ALTER TABLE user
CHANGE userId id INT UNSIGNED AUTO_INCREMENT NOT NULL,
CHANGE username username VARCHAR(32) NOT NULL COLLATE utf8mb4_bin,
CHANGE password password LONGTEXT NOT NULL COLLATE utf8mb4_bin,
CHANGE salt salt CHAR(32) NOT NULL COLLATE utf8mb4_bin,
CHANGE creationTimestamp creation_date_time DATETIME NOT NULL,
CHANGE connectionTimestamp connection_date_time DATETIME DEFAULT NULL,
DROP usedDiskSpace,
DROP totalDiskSpace;

ALTER TABLE user_has_role
CHANGE userId user_id INT UNSIGNED NOT NULL,
CHANGE role role ENUM('ROLE_USER', 'ROLE_ADMIN') NOT NULL COLLATE utf8mb4_bin;

ALTER TABLE sharing
CHANGE token token CHAR(32) NOT NULL COLLATE utf8mb4_bin,
CHANGE userId user_id INT UNSIGNED DEFAULT NULL,
CHANGE path path LONGTEXT NOT NULL COLLATE utf8mb4_bin,
CHANGE creationTimestamp  creation_date_time DATETIME NOT NULL;

ALTER TABLE user ENGINE=InnoDB;

ALTER TABLE user_has_role ENGINE=InnoDB;
ALTER TABLE user_has_role ADD CONSTRAINT FK_5BB02BA1A76ED395 FOREIGN KEY (user_id) REFERENCES User (id) ON DELETE CASCADE;
ALTER TABLE user_has_role RENAME INDEX userid TO IDX_5BB02BA1A76ED395;

ALTER TABLE sharing ENGINE=InnoDB;
ALTER TABLE sharing ADD CONSTRAINT FK_613CD5F4A76ED395 FOREIGN KEY (user_id) REFERENCES User (id) ON DELETE CASCADE;
ALTER TABLE sharing RENAME INDEX userid TO IDX_613CD5F4A76ED395;
ALTER TABLE sharing RENAME INDEX creationtimestamp TO IDX_613CD5F49EFE38B4;
DROP INDEX path ON sharing;
