
USE athorrent;

RENAME TABLE user_role TO userhasrole;

ALTER TABLE user
CHANGE userId id INT UNSIGNED AUTO_INCREMENT NOT NULL,
CHANGE username username VARCHAR(32) NOT NULL COLLATE utf8_bin,
CHANGE password password CHAR(88) NOT NULL COLLATE utf8_bin,
CHANGE salt salt CHAR(32) NOT NULL COLLATE utf8_bin,
CHANGE creationTimestamp creationDateTime DATETIME NOT NULL,
CHANGE connectionTimestamp connectionDateTime DATETIME DEFAULT NULL,
DROP usedDiskSpace,
DROP totalDiskSpace;

ALTER TABLE userhasrole
CHANGE userId user_id INT UNSIGNED NOT NULL,
CHANGE role role ENUM('ROLE_USER', 'ROLE_ADMIN') NOT NULL COLLATE utf8_bin;

ALTER TABLE sharing
CHANGE token token CHAR(32) NOT NULL COLLATE utf8_bin,
CHANGE userId user_id INT UNSIGNED DEFAULT NULL,
CHANGE path path LONGTEXT NOT NULL COLLATE utf8_bin,
CHANGE creationTimestamp  creationDateTime DATETIME NOT NULL;

ALTER TABLE user ENGINE=InnoDB;

ALTER TABLE userhasrole ENGINE=InnoDB;
ALTER TABLE userhasrole ADD CONSTRAINT FK_5BB02BA1A76ED395 FOREIGN KEY (user_id) REFERENCES User (id) ON DELETE CASCADE;
ALTER TABLE userhasrole RENAME INDEX userid TO IDX_5BB02BA1A76ED395;

ALTER TABLE sharing ENGINE=InnoDB;
ALTER TABLE sharing ADD CONSTRAINT FK_613CD5F4A76ED395 FOREIGN KEY (user_id) REFERENCES User (id) ON DELETE CASCADE;
ALTER TABLE sharing RENAME INDEX userid TO IDX_613CD5F4A76ED395;
ALTER TABLE sharing RENAME INDEX creationtimestamp TO IDX_613CD5F49EFE38B4;
DROP INDEX path ON sharing;
