<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250302082710 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE sharing (token CHAR(32) NOT NULL, path TEXT NOT NULL, creation_date_time TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT DEFAULT NULL, PRIMARY KEY(token))');
        $this->addSql('CREATE INDEX IDX_AE81EC68A76ED395 ON sharing (user_id)');
        $this->addSql('CREATE INDEX IDX_AE81EC68A19E3024 ON sharing (creation_date_time)');
        $this->addSql('CREATE INDEX IDX_AE81EC68A76ED395B548B0F ON sharing (user_id, path)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(32) NOT NULL, password TEXT NOT NULL, salt CHAR(32) NOT NULL, creation_date_time TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, connection_date_time TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, port INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX username ON "user" (username)');
        $this->addSql('CREATE UNIQUE INDEX port ON "user" (port)');
        $this->addSql('CREATE TABLE user_has_role (role VARCHAR(255) NOT NULL, user_id INT NOT NULL, PRIMARY KEY(user_id, role))');
        $this->addSql('CREATE INDEX IDX_EAB8B535A76ED395 ON user_has_role (user_id)');
        $this->addSql('ALTER TABLE sharing ADD CONSTRAINT FK_AE81EC68A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_has_role ADD CONSTRAINT FK_EAB8B535A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE sharing DROP CONSTRAINT FK_AE81EC68A76ED395');
        $this->addSql('ALTER TABLE user_has_role DROP CONSTRAINT FK_EAB8B535A76ED395');
        $this->addSql('DROP TABLE sharing');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE user_has_role');
    }
}
