
volumes:
    jackett_data:

services:
    jackett:
        image: linuxserver/jackett:latest
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Paris
            - AUTO_UPDATE=false #optional
        volumes:
            - jackett_data:/config
        restart: unless-stopped

    php:
        build:
            context: ..
            dockerfile: docker/Dockerfile
            target: dev
        depends_on:
            - jackett
        volumes:
            - ..:/var/www/athorrent
            - /var/run/docker.sock:/var/run/docker.sock
            - ./spx.ini:/usr/local/etc/php/conf.d/spx.ini:ro

    nginx:
        build:
            context: ..
            dockerfile: docker/Dockerfile
            target: nginx-base
        depends_on:
            - php
        volumes:
            - ..:/var/www/athorrent:ro

    reverse-proxy:
        image: caddy
        depends_on:
            - nginx
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile:ro
        ports:
            - "80:80"
            - "443:443"
