
x-php-base: &php-base
    build:
        context: ../..
        dockerfile: docker/Dockerfile
        target: php
    env_file:
        - ../../.env
    volumes:
        - db_data:/var/www/athorrent/var/lib
        - user_data:/var/www/athorrent/var/user

services:
    backend-manager:
        <<: *php-base

    php:
        <<: *php-base
