
volumes:
    user_data:

services:
    php:
        build:
            args: &build_args
                - SYMFONY_APP_ENV=test
                - COMPOSER_ARGS=
        env_file:
            - ../../.env.test
        volumes:
            - user_data:/var/www/athorrent/var/user

    nginx:
        build:
            args: *build_args
        volumes:
            - user_data:/var/www/athorrent/var/user:ro
