
configs:
    caddy_config:
        file: ./conf/caddy/Caddyfile

services:
    jackett:
        image: linuxserver/jackett:latest
        hostname: athorrent-jackett
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Paris
        volumes:
            - ./conf/jackett/:/ro-config/:ro
        entrypoint: >
            bash -c "
                cp -r /ro-config/. /config/Jackett
                chown -R 1000:1000 /config;
                exec /init
            "

    php:
        build:
            context: ../..
            dockerfile: docker/Dockerfile
            target: php
        hostname: athorrent-php
        depends_on:
            - jackett
        env_file:
            - ../../.env
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

    nginx:
        build:
            context: ../..
            dockerfile: docker/Dockerfile
            target: nginx
        hostname: athorrent-nginx
        depends_on:
            - php

    reverse-proxy:
        image: caddy
        hostname: athorrent-caddy
        depends_on:
            - nginx
        configs:
            - source: caddy_config
              target: /etc/caddy/Caddyfile
        ports:
            - "80:80"
            - "443:443"
