
configs:
    caddy_config:
        file: ./conf/caddy/Caddyfile

x-php-base: &php-base
    build:
        context: ../..
        dockerfile: docker/Dockerfile
        target: php
    env_file:
        - ../../.env

services:
    jackett:
        image: linuxserver/jackett:latest
        hostname: athorrent-jackett
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Paris
        volumes:
            - ./conf/jackett/:/ro-config/:ro
        entrypoint: >
            bash -c "
                cp -r /ro-config/. /config/Jackett
                chown -R 1000:1000 /config;
                exec /init
            "

    backend-manager:
        <<: *php-base
        user: root
        entrypoint: php
        command: [ 'bin/console', 'backend-manager:run', '-vv' ]
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

    php:
        <<: *php-base
        hostname: athorrent-php
        depends_on:
            - jackett

    nginx:
        build:
            context: ../..
            dockerfile: docker/Dockerfile
            target: nginx
        hostname: athorrent-nginx
        depends_on:
            - php

    reverse-proxy:
        image: caddy
        hostname: athorrent-caddy
        depends_on:
            - nginx
        configs:
            - source: caddy_config
              target: /etc/caddy/Caddyfile
        ports:
            - "80:80"
            - "443:443"
