
x-php-base: &php-base
    build:
        args: &build_args
            - SYMFONY_APP_ENV=test
            - COMPOSER_ARGS=
    env_file:
        - ../../.env.test

services:
    backend-manager:
        <<: *php-base

    php:
        <<: *php-base

    nginx:
        build:
            args: *build_args

