
services:
    php:
        build:
            args: &build_args
                - APP_ENV=test
                - COMPOSER_ARGS=
        env_file:
            - ../../.env.test

    nginx:
        build:
            args: *build_args
